-- Widen pitch sizes from {5, 7, 11}-a-side to the full 5-11 range.
ALTER TYPE "PitchType" ADD VALUE 'SIX_A_SIDE' BEFORE 'SEVEN_A_SIDE';
ALTER TYPE "PitchType" ADD VALUE 'EIGHT_A_SIDE' AFTER 'SEVEN_A_SIDE';
ALTER TYPE "PitchType" ADD VALUE 'NINE_A_SIDE' AFTER 'EIGHT_A_SIDE';
ALTER TYPE "PitchType" ADD VALUE 'TEN_A_SIDE' AFTER 'NINE_A_SIDE';
